# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Vendor.destroy_all
Vendor.create!(name:'Badger Wholesale')
Vendor.create!(name:'Empire Fish')
Vendor.create!(name:'Sysco')

Category.destroy_all
Ingredient.destroy_all
refrigerated      = Category.create( name: 'Refrigerated')

#refrigerated > dairy
dairy             = refrigerated.children.build(name:'Dairy'  )  
                    dairy.ingredients.build(name: 'Butter'    )  
                    cheese  = dairy.ingredients.build(name: 'Cheese'    ) 
                              cheese.ingredients.build(name: 'Cheese, Cheddar')
                              cheese.ingredients.build(name: 'Cheese, Parmesan')
                              cheese.ingredients.build(name: 'Cheese, Goat')
                    dairy.ingredients.build(name: 'Cream, Sour') 
                    dairy.ingredients.build(name: 'Cream, Heavy Whipping')
                    dairy.ingredients.build(name: 'Milk, Whole')
                    dairy.ingredients.build(name: 'Milk, 2%')
                    dairy.ingredients.build(name: 'Milk, Skim')
                    dairy.ingredients.build(name: 'Milk, Chocolate')

#refrigerated > produce
produce           = refrigerated.children.build(name:'Produce')
  herb            = produce.children.build(name:'Herb')
                    herb.ingredients.build(name: 'Parsley, Fresh')
                    herb.ingredients.build(name: 'Rosemary, Fresh')
                    herb.ingredients.build(name: 'Sage, Fresh')
                    herb.ingredients.build(name: 'Thyme, Fresh')
                    herb.ingredients.build(name: 'Cilantro, Fresh')
  fruit           = produce.children.build(name:'Fruit')
                    fruit.ingredients.build(name: 'Avocado')
                    fruit.ingredients.build(name: 'Cucumber')
                    fruit.ingredients.build(name: 'Okra')
                    fruit.ingredients.build(name: 'Pepper')
                    fruit.ingredients.build(name: 'Pepper, Bell, Red')
                    fruit.ingredients.build(name: 'Pepper, Bell, Yellow')
                    fruit.ingredients.build(name: 'Pepper, Bell, Orange')
                    fruit.ingredients.build(name: 'Pepper, Bell, Green')
                    fruit.ingredients.build(name: 'Pepper, Jalepeno')
                    fruit.ingredients.build(name: 'Pepper, Banana')
                    fruit.ingredients.build(name: 'Pumpkin')
                    fruit.ingredients.build(name: 'Snap Beans')
                    fruit.ingredients.build(name: 'Squash')
                    tomato  = fruit.ingredients.build(name: 'Tomato')
                              fruit.ingredients.build(name: 'Tomato, Cherry')
                              fruit.ingredients.build(name: 'Tomato, Grape')
                    fruit.ingredients.build(name: 'Strawberry')
                    fruit.ingredients.build(name: 'Raspberry')
                    fruit.ingredients.build(name: 'Blueberry')
                    fruit.ingredients.build(name: 'Blackberry')
                    fruit.ingredients.build(name: 'Cherry')
                    fruit.ingredients.build(name: 'Banana')
                    fruit.ingredients.build(name: 'Orange')
                    fruit.ingredients.build(name: 'Apple')
                    fruit.ingredients.build(name: 'Lime')
                    fruit.ingredients.build(name: 'Lemon')
    juice         = fruit.children.build(name: 'Juice')
                    juice.ingredients.build(name: 'Juice, Lime')
                    juice.ingredients.build(name: 'Juice, Lemon')
                    juice.ingredients.build(name: 'Juice, Apple')
                    juice.ingredients.build(name: 'Juice, Orange')
                    juice.ingredients.build(name: 'Juice, Cherry')
                    juice.ingredients.build(name: 'Juice, Pineapple')

  vegetable       = produce.children.build(name:'Vegetable')
                    vegetable.ingredients.build(name: 'Brocolli')
                    vegetable.ingredients.build(name: 'Cauliflower')
    roots_tubers  = vegetable.children.build(name:'Roots and Tubers')
                    beet    = roots_tubers.ingredients.build(name: 'Beet')
                              roots_tubers.ingredients.build(name: 'Beet, Red')
                              roots_tubers.ingredients.build(name: 'Beet, Golden')
                    roots_tubers.ingredients.build(name: 'Carrot')
                    roots_tubers.ingredients.build(name: 'Radish')
                    roots_tubers.ingredients.build(name: 'Rutabaga')
                    roots_tubers.ingredients.build(name: 'Radish')
                    roots_tubers.ingredients.build(name: 'Turnip')
                    roots_tubers.ingredients.build(name: 'Yam')
                    roots_tubers.ingredients.build(name: 'Ginger Root')
                    potato  = roots_tubers.ingredients.build(name: 'Potato')
                              roots_tubers.ingredients.build(name: 'Potato, Red')
                              roots_tubers.ingredients.build(name: 'Potato, Fingerling')
                              roots_tubers.ingredients.build(name: 'Potato, Sweet')
                              roots_tubers.ingredients.build(name: 'Potato, Baking')
                    roots_tubers.ingredients.build(name: 'Sunchoke')
                    roots_tubers.ingredients.build(name: 'Jicama')
                    roots_tubers.ingredients.build(name: 'Parsnip')
         
    stem          = vegetable.children.build(name:'Stem')
                    stem.ingredients.build(name: 'Asparagus')
                    stem.ingredients.build(name: 'Kohlarabi')
                    stem.ingredients.build(name: 'Celery')
                    stem.ingredients.build(name: 'Fennel')
    leaf          = vegetable.children.build(name:'Leaf and Leaf-Stalk')
                    leaf.ingredients.build(name: 'Brussels Sprouts')
                    leaf.ingredients.build(name: 'Cabbage')
                    leaf.ingredients.build(name: 'Celery')
                    leaf.ingredients.build(name: 'Chard')
                    leaf.ingredients.build(name: 'Chicory')
                    leaf.ingredients.build(name: 'Endive')
                    leaf.ingredients.build(name: 'Lettuce')
                    leaf.ingredients.build(name: 'Rhubarb')
                    leaf.ingredients.build(name: 'Spinach')
                    leaf.ingredients.build(name: 'Bok Choi')
                    leaf.ingredients.build(name: 'Collards')
                    leaf.ingredients.build(name: 'Escarole')
                    leaf.ingredients.build(name: 'Kale')
                    leaf.ingredients.build(name: 'Mustard Greens')
                    leaf.ingredients.build(name: 'Romaine')
                    leaf.ingredients.build(name: 'Watercress')
    bulb          = vegetable.children.build(name:'Bulb')
                    bulb.ingredients.build(name: 'Garlic')
                    bulb.ingredients.build(name: 'Leek')
                    bulb.ingredients.build(name: 'Onion')
                    bulb.ingredients.build(name: 'Chives')
                    bulb.ingredients.build(name: 'Shallot')
    legume        = vegetable.children.build(name:'Legume')
                    legume.ingredients.build(name: 'Beans')
                    legume.ingredients.build(name: 'Corn')
                    legume.ingredients.build(name: 'Lentils')
                    legume.ingredients.build(name: 'Lentils, Brown')
                    legume.ingredients.build(name: 'Lentils, Green')
                    legume.ingredients.build(name: 'Lentils, Red')
                    legume.ingredients.build(name: 'Lentils, Black')
                    legume.ingredients.build(name: 'Peas')
                    
    fungi         = refrigerated.children.build(name:'Fungi')
                    fungi.ingredients.build(name: 'Mushroom, White')
                    fungi.ingredients.build(name: 'Mushroom, Chanterelle')
                    fungi.ingredients.build(name: 'Mushroom, Oyster')
                    fungi.ingredients.build(name: 'Mushroom, Portabello')
                    fungi.ingredients.build(name: 'Mushroom, Shiitake')
                    fungi.ingredients.build(name: 'Mushroom, Cremini')
                    fungi.ingredients.build(name: 'Mushroom, Morel')
                    fungi.ingredients.build(name: 'Mushroom, Hen-of-the-woods')

  meat            = refrigerated.children.build(name:'Meat')
    beef          = meat.children.build(name:'Beef')
                    beef.ingredients.build(name:'Beef: Whole Cow')
                    chuck       = beef.ingredients.build(name:'Beef: Chuck')
                    rib         = beef.ingredients.build(name:'Beef: Rib')
                                  beef.ingredients.build(name:'Beef: Rib Roast, Large End')
                                  beef.ingredients.build(name:'Beef: Rib Roast, Small End')
                                  beef.ingredients.build(name:'Beef: Rib Steak, Small End')
                                  beef.ingredients.build(name:'Beef: Rib Eye Steak')
                                  beef.ingredients.build(name:'Beef: Rib Eye Roast')
                                  beef.ingredients.build(name:'Beef: Back Ribs')
                    short_loin  = beef.ingredients.build(name:'Beef: Short Loin')
                                  beef.ingredients.build(name:'Beef: Top Loin Steak')
                                  beef.ingredients.build(name:'Beef: T-Bone Steak')
                                  beef.ingredients.build(name:'Beef: Porterhouse Steak')
                                  beef.ingredients.build(name:'Beef: Tenderloin Roast/Steak')
                    sirloin     = beef.ingredients.build(name:'Beef: Sirloin')
                                  beef.ingredients.build(name:'Beef: Top Sirloin Steak')
                                  beef.ingredients.build(name:'Beef: Sirloin Steak')
                                  beef.ingredients.build(name:'Beef: Tenderloing Roast/Steak')
                                  beef.ingredients.build(name:'Beef: Tri-Tip')
                    round       = beef.ingredients.build(name:'Beef: Round')
                                  beef.ingredients.build(name:'Beef: Round Steak')
                                  beef.ingredients.build(name:'Beef: Top Round Roast')
                                  beef.ingredients.build(name:'Beef: Top Round Steak')
                                  beef.ingredients.build(name:'Beef: Bottom Round Roast')
                                  beef.ingredients.build(name:'Beef: Tip Roast Cap Off')
                                  beef.ingredients.build(name:'Beef: Eye Round Roast')
                                  beef.ingredients.build(name:'Beef: Tip Steak')
                                  beef.ingredients.build(name:'Beef: Boneless Rump Roast')
                    flank       = beef.ingredients.build(name:'Beef: Flank')
                                  beef.ingredients.build(name:'Beef: Flank Steak')
                                  beef.ingredients.build(name:'Beef: Flank Steak Rolls')
                    plate       = beef.ingredients.build(name:'Beef: Plate')
                                  beef.ingredients.build(name:'Beef: Skirt Steak')
                    shank       = beef.ingredients.build(name:'Beef: Shank')
                    brisket     = beef.ingredients.build(name:'Beef: Brisket')
                                  beef.ingredients.build(name:'Beef: Whole Brisket')
                                  beef.ingredients.build(name:'Beef: Brisket, Point Half')
                                  beef.ingredients.build(name:'Beef: Brisket, Flat Half')
    pork          = meat.children.build(name:'Pork')
                    pork.ingredients.build(name:'Pork: Whole Pig')
                    pork.ingredients.build(name:'Pork: Jowl')
                    pork.ingredients.build(name:'Pork: Bacon Square')
                    pork.ingredients.build(name:'Pork: Smoked Cottage Roll')
                    pork.ingredients.build(name:'Pork: Butt')
                    pork.ingredients.build(name:'Pork: Boston Style Butt')
                    pork.ingredients.build(name:'Pork: Blade Steak')
                    pork.ingredients.build(name:'Pork: Lard')
                    pork.ingredients.build(name:'Pork: Loin Roast')
                    pork.ingredients.build(name:'Pork: Chop')
                    pork.ingredients.build(name:'Pork: Sirloin Roast')
                    pork.ingredients.build(name:'Pork: Tenderloin')
                    pork.ingredients.build(name:'Pork: Ham')
                    pork.ingredients.build(name:'Pork: Half Ham')
                    pork.ingredients.build(name:'Pork: Ham Slice')
                    pork.ingredients.build(name:'Pork: Fresh Ham Roast')
                    pork.ingredients.build(name:'Pork: Bacon')
                    pork.ingredients.build(name:'Pork: Spareribs')
                    pork.ingredients.build(name:'Pork: Fresh Picnic Shoulder')
                    pork.ingredients.build(name:'Pork: Arm Steak')
                    pork.ingredients.build(name:'Pork: Fresh Shoulder Hock')
    poultry       = meat.children.build(name:'Poultry')  
                    chicken     = poultry.ingredients.build(name:'Whole Chicken')
                                  poultry.ingredients.build(name:'Chicken: Whole Leg')
                                  poultry.ingredients.build(name:'Chicken: Leg Quarter')
                                  poultry.ingredients.build(name:'Chicken: Drumstick')
                                  poultry.ingredients.build(name:'Chicken: Breast, Skin-on, Bone-in')
                                  poultry.ingredients.build(name:'Chicken: Breast, Skin-less, Fillet')
                                  poultry.ingredients.build(name:'Chicken: 3-Joint Wing')
                                  poultry.ingredients.build(name:'Chicken: Wing Tip')
                                  poultry.ingredients.build(name:'Chicken: Mid-Joint Wing')
                                  poultry.ingredients.build(name:'Chicken: Forequarter')
                                  poultry.ingredients.build(name:'Chicken: Thigh')
                                  poultry.ingredients.build(name:'Chicken: Giblets')
                                  poultry.ingredients.build(name:'Chicken: Neck')
                                  poultry.ingredients.build(name:'Chicken: Gizzard')
                                  poultry.ingredients.build(name:'Chicken: Kidney')
                                  poultry.ingredients.build(name:'Chicken: Livers')
                                  poultry.ingredients.build(name:'Chicken: Heart')
                    turkey      = poultry.ingredients.build(name:'Whole Turkey')
                                  poultry.ingredients.build(name:'Turkey: Giblets')
                                  poultry.ingredients.build(name:'Turkey: Legs')
                    duck        = poultry.ingredients.build(name:'Whole Duck')
       seafood      = refrigerated.children.build(name:'Seafood')             
                     
  
refrigerated.save


dry_goods           = Category.create(name:'Dry Goods'                                  )
  spices            = dry_goods.children.build(name:'Spices'                            )
                      sugar   = spices.ingredients.build(name:'Sugar'                   )
                                spices.ingredients.build(name:'Sugar, Granulated'       )
                                spices.ingredients.build(name:'Sugar, Brown'            )
                      salt    = spices.ingredients.build(name:'Salt'                    )
                                spices.ingredients.build(name:'Salt, Iodized'           )
                                spices.ingredients.build(name:'Salt, Sea'               )
                                spices.ingredients.build(name:'Salt, Kosher'            )
                                spices.ingredients.build(name:'Salt, Seasoned'          )
                                spices.ingredients.build(name:'Salt, Celery'            )
                      pepper  = spices.ingredients.build(name:'Pepper (spice)'          )
                                spices.ingredients.build(name:'Pepper, Black'           )
                                spices.ingredients.build(name:'Pepper, White'           )
                      
                      
  oils_vinegars     = dry_goods.children.build(name:'Oils, Vinegars, Sauces')
                      oils_vinegars.ingredients.build(name:'Honey')
                      oils_vinegars.ingredients.build(name:'Vinegar, White Distilled')
                      oils_vinegars.ingredients.build(name:'Vinegar, Red Wine')
                      oils_vinegars.ingredients.build(name:'Vinegar, Rice Wine')
                      oils_vinegars.ingredients.build(name:'Olive Oil, Extra Virgin')
                      oils_vinegars.ingredients.build(name:'Corn Syrup')
                      oils_vinegars.ingredients.build(name:'Worcestershire Sauce')
                      oils_vinegars.ingredients.build(name:'Soy Sauce')
                      
                      
                      
    
  grains            = dry_goods.children.build(name:'Grains')
                      grains.ingredients.build(name:'Flour')
    whole_grains    = grains.children.build(name:'Whole')
                      whole_grains.ingredients.build(name:'Amaranth')
                      whole_grains.ingredients.build(name:'Barley')
                      whole_grains.ingredients.build(name:'Rice, Brown')
                      whole_grains.ingredients.build(name:'Rice, Refined')
                      whole_grains.ingredients.build(name:'Rice, White')
                      whole_grains.ingredients.build(name:'Rice, Wild')
                      whole_grains.ingredients.build(name:'Rice, Jasmine')
                      whole_grains.ingredients.build(name:'Rice, Basmati')
                      whole_grains.ingredients.build(name:'Buckwheat')
                      whole_grains.ingredients.build(name:'Bulgur(Cracked Wheat)')
                      whole_grains.ingredients.build(name:'Farro')
                      whole_grains.ingredients.build(name:'Flaxseed')
                      whole_grains.ingredients.build(name:'Grano')
                      whole_grains.ingredients.build(name:'Oats')
                      whole_grains.ingredients.build(name:'Popcorn')
    refined_grains  = grains.children.build(name:'Refined')
                      refined_grains.ingredients.build(name:'Couscous')
                      refined_grains.ingredients.build(name:'Qunioa')
                      refined_grains.ingredients.build(name:'Grits')
                      refined_grains.ingredients.build(name:'Noodles')

dry_goods.save

Measure.destroy_all
measures = Measure.create(
  [
    {name: 'Gallon',      abbreviation: 'gal',  volume_weight: 0,   english_metric: 0 },  #0
    {name: 'Quart',       abbreviation: 'qt',   volume_weight: 0,   english_metric: 0 },  #1
    {name: 'Pint',        abbreviation: 'pt',   volume_weight: 0,   english_metric: 0 },  #2
    {name: 'Cup',         abbreviation: 'c',    volume_weight: 0,   english_metric: 0 },  #3
    {name: 'Ounce (vol)', abbreviation: 'oz',   volume_weight: 0,   english_metric: 0 },  #4
    {name: 'Tablespoon',  abbreviation: 'tbsp', volume_weight: 0,   english_metric: 0 },  #5
    {name: 'Teaspoon',    abbreviation: 'tsp',  volume_weight: 0,   english_metric: 0 },  #6
    {name: 'Liter',       abbreviation: 'L',    volume_weight: 0,   english_metric: 1 },  #7
    {name: 'Pound',       abbreviation: 'lb',   volume_weight: 1,   english_metric: 0 },  #8
    {name: 'Ounce (wt)',  abbreviation: 'oz',   volume_weight: 1,   english_metric: 0 },  #9
    {name: 'gram',        abbreviation: 'g',    volume_weight: 0,   english_metric: 1 }   #10
  ]

)
Conversion.destroy_all
Conversion.create(
  [
    { measure_a_id: measures[0].id,  measure_b_id: measures[1].id,    quantity: 4.0       }, # gal = 4.0 qt (s)
    { measure_a_id: measures[0].id,  measure_b_id: measures[2].id,    quantity: 8.0       }, # gal = 8.0 pt (s)
    { measure_a_id: measures[0].id,  measure_b_id: measures[3].id,    quantity: 16.0      }, # gal = 16.0 c (s)
    { measure_a_id: measures[0].id,  measure_b_id: measures[4].id,    quantity: 128.0     }, # gal = 128.0 oz (s)
    { measure_a_id: measures[0].id,  measure_b_id: measures[7].id,    quantity: 3.78541   }, # gal = 3.78541 L (s)
    
    { measure_a_id: measures[1].id,  measure_b_id: measures[2].id,    quantity: 2.0       }, # qt = 2.0 pt (s)
    { measure_a_id: measures[1].id,  measure_b_id: measures[3].id,    quantity: 4.0       }, # qt = 4.0 c (s)
    { measure_a_id: measures[1].id,  measure_b_id: measures[4].id,    quantity: 32.0      }, # qt = 32.0 oz (s)
    { measure_a_id: measures[1].id,  measure_b_id: measures[7].id,    quantity: 0.96      }, # qt = 0.96 L (s)
    
    { measure_a_id: measures[2].id,  measure_b_id: measures[3].id,    quantity: 2.0       }, # pt = 2.0 c (s)
    { measure_a_id: measures[2].id,  measure_b_id: measures[4].id,    quantity: 16.0      }, # pt = 16.0 oz (s)
    { measure_a_id: measures[2].id,  measure_b_id: measures[7].id,    quantity: 0.48      }, # pt = 0.48 L (s)
    
    { measure_a_id: measures[3].id,  measure_b_id: measures[4].id,    quantity: 8.0       }, # c = 8.0 oz (s)
    { measure_a_id: measures[3].id,  measure_b_id: measures[5].id,    quantity: 16.0      }, # c = 16.0 tbsp (s)
    { measure_a_id: measures[3].id,  measure_b_id: measures[7].id,    quantity: 0.238588  }, # c = 0.238588 L (s)
    
    { measure_a_id: measures[4].id,  measure_b_id: measures[5].id,    quantity: 2.0       }, # oz = 2.0 tbsp (s)
    { measure_a_id: measures[4].id,  measure_b_id: measures[7].id,    quantity: 0.03      }, # oz = 0.03 L (s)
    
    { measure_a_id: measures[5].id,  measure_b_id: measures[6].id,    quantity: 3.0       }, # tbsp = 3.0 tsp (s)
    
    { measure_a_id: measures[6].id,  measure_b_id: measures[7].id,    quantity: 0.005     }, # tsp = 0.005 L (s)
    
    { measure_a_id: measures[8].id,  measure_b_id: measures[9].id,    quantity: 16.0      }, # lb = 16.0 oz (s)
    { measure_a_id: measures[8].id,  measure_b_id: measures[10].id,   quantity: 453.592  } # lb = 453.592 g (s)
    
  ]

)

